---
  - name: Configure catalogue server
    hosts: catalogue
    become: yes

    tasks:
    - name: Disable default nodejs module
      ansible.builtin.command: dnf module disable nodejs -y 

    - name: Enable nodejs 20 module
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present  

    - name: Create roboshop system user for catalogue
      ansible.builtin.user:
        name: roboshop
        shell: /bin/bash
        system: yes
        home: /app

    - name: Create app directory
      ansible.builtin.file:
        name: /app
        state: directory

    - name: Download catalogue source code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: Unzip catalogue source code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install npm dependencies
      community.general.npm:
        path: /app
    
    - name: copy catalogue service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service
        mode: '0644'

    - name: Reload systemd to recognize new service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable catalogue service
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes
    
    - name: Ensure catalogue service is running
      ansible.builtin.command: systemctl status catalogue
      register: catalogue_status
      failed_when: "'Active: active (running)' not in catalogue_status.stdout"
      changed_when: false
    
    - name: copy mongodb repo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo
    
    - name: Install mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: check if products data is loaded
      ansible.builtin.command: mongosh --host mongodb.rameshaws.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: load_products_data

    - name: print products data load status
      ansible.builtin.debug:
        msg: "{{ load_products_data }}"
    
    - name: Load products 
      ansible.builtin.shell: mongosh --host mongodb.rameshaws.site < /app/db/master-data.js
      when: load_products_data.stdout | int < 0  
